---
- name: GetApp - Ensure developer has a copy of the app directory where he/she wants it
  hosts: localhost
  become: no
  vars_files:
  - splunk_vault.yml
  - vars/single_app_vars.yml

  tasks:
  - name: GetApp - Create {{ sapp_edit_path }} directory on localhost
    file:
      dest: "{{ sapp_edit_path }}"
      state: directory
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'
        
- name: GetApp - Get application from deployer
  hosts: deployer
  become: yes
  become_user: "{{ sapp.splunk_prog.admin_user }}"
  vars_files:
  - splunk_vault.yml
  - vars/single_app_vars.yml
  
  tasks:
    - include_tasks: tasks/pull_app.yml

- name: GetApp - Unarchive the pulled bz2ball
  hosts: localhost
  become: no
  vars_files:
  - splunk_vault.yml
  - vars/single_app_vars.yml

  tasks:
  - name: GetApp - Unarchive {{ sapp_name }}.bz2 to {{ sapp_name }} directory on localhost
    unarchive:
      src: "{{ sapp_edit_path }}/{{ sapp_name }}.bz2"
      dest: "{{ sapp_edit_path }}/"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'