---
- name: GetApp - Ensure developer has a copy of the app directory where he/she wants it
  hosts: localhost
  become: no
  vars_files:
  - vars/splunk_vault.yml
  - vars/single_app_vars.yml
  tasks:
  - name: GetApp - Create {{ splunk_app.edit_path }} directory on localhost
    file:
      dest: "{{ splunk_app.edit_path }}"
      state: directory
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'
        
- name: GetApp - Get application from deployer
  hosts: deployer
  become: yes
  become_user: "{{ splunk.admin.user }}"
  vars_files:
  - vars/splunk_vault.yml
  - vars/single_app_vars.yml
  tasks:
    - include_tasks: tasks/pull_app.yml

- name: GetApp - Unarchive the pulled bz2ball
  hosts: localhost
  become: no
  vars_files:
  - vars/splunk_vault.yml
  - vars/single_app_vars.yml
  tasks:
  - name: GetApp - Unarchive {{ splunk_app.name }}.bz2 to {{ splunk_app.name }} directory on localhost
    unarchive:
      src: "{{ splunk_app.edit_path }}/{{ splunk_app.name }}.bz2"
      dest: "{{ splunk_app.edit_path }}/"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'