---
# The following playbook assumes [despite what assuming does] that the apps tree is populated.
# ... If not, then the reloading of the deployment server will uninstall this application

- name: PutApp - Create archive on local server of app tree
  hosts: localhost
  become: no
  vars_files:
  - vars/splunk_vault.yml
  - vars/single_app_vars.yml
  #See "archive-doc archive" for src & dest. e.g's.
  tasks:
  - name: PutApp - Create archive localhost:"{{ splunk_app.edit_path }}/{{ splunk_app.name }}".bz2
    archive:
      path: "{{ splunk_app.edit_path }}/"
      dest: "{{ splunk_app.edit_path }}/{{ splunk_app.name }}.bz2"
      format: bz2
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'

- name: PutApp - Deploy a single (manually) update app
  hosts: deployer
  become: yes
  become_user: "{{ splunk_prog.admin_user }}"
  vars_files:
  - vars/splunk_vault.yml
  - vars/single_app_vars.yml
  tasks:
      - include_tasks: tasks/push_app.yml
      - include_tasks: tasks/initate_deployment.yml

# According to Splunk's documentation for ver 8.0.4 [https://docs.splunk.com/Documentation/Splunk/8.0.4/Updating/Updateconfigurations]
# ... we don't need to restart splunk, hence the lines below are commented out...
  # - pause:
  #   minutes: 1  
# 
# - name: PutApp - Restart splunk on servers that require it
#   hosts: all
#   become: yes
  # tasks:
  #   - include_tasks: 
#       tasks/check_for_required_restarts.yml
  # 
#   - name: PutApp - Restart if required
#     service:
#       name: "{{ splunk_app.service.svc }}"
#       state: restarted
