---
# The following playbook assumes [despite what assuming does] that the apps tree is populated.
# ... If not, then the reloading of the deployment server will uninstall this application

- name: Create archive on local server of app tree
  hosts: localhost
  become: no
  #See "archive-doc archive" for src & dest. e.g's.
  tasks:
  - name: Create archive localhost:{{ sapp.edit.path }}/{{ sapp.name }}.bz2
    archive:
      path: "{{ sapp.edit.path }}/"
      dest: "{{ sapp.edit.path }}/{{ sapp.name }}.bz2"
      format: bz2
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'

- name: Deploy a single (manually) update app
  hosts: deployer
  become: yes
  become_user: "{{ splunk.user }}"
  vars_files:
    - splunk_vault.yml
    - vars/single_app_vars.yml
  tasks:
    # Copy app to deployer server via archive
      - include_tasks: tasks/push_app.yml

    # Intiate deployment on deployment server via reload of deployer server
      - include_tasks: tasks/initate_deployment.yml

# According to Splunk's documentation for ver 8.0.4 [https://docs.splunk.com/Documentation/Splunk/8.0.4/Updating/Updateconfigurations]
# ... we don't need to restart splunk, hence the lines below are commented out...
  # - pause:
  #   minutes: 1  
# 
# - name: Restart splunk on servers that require it
#   hosts: all
#   become: yes
#   tasks:
#   - name: Check whether splunk restart required
#     include_tasks: 
#       tasks/check_for_required_restarts.yml
  # 
#   - name: Restart if required
#     service:
#       name: "{{ splunk.service }}"
#       state: restarted
