---
# The following playbook assumes [despite what assuming does] that the apps tree is populated.
# ... If not, then the reloading of the deployment server will uninstall all the missing applications

- name: Deploy a single (manually) update app)
  become_user: splunk
  hosts: deployer
  vars_files:
  - splunk_vault.yml
  tasks:
    - include_tasks: tasks/place_single_app.yml
    - include_tasks: tasks/check_for_required_restarts.yml

- name: Ensure developer's copy of the app directory is removed
  hosts: localhost
  become: no
  tasks:
  - name: Remove {{ sapp.edit.path }} directory on localhost
    file:
      dest: "{{ sapp.edit.path }}"
      state: absent