- name: Archive app tree on deployment server
#See "archive-doc archive" for src & dest. e.g's.
  archive:
    path: "{{ sapp.location }}/{{ sapp.name }}"
    dest: "{{ sapp.tempfile.archname }}"
    format: bz2

- name: Fetch archived app from deployer
  fetch:
    src: "/var/tmp/{{ sapp.name }}.bz2"
    dest: "{{ sapp.edit.path }}/{{ sapp.name }}.bz2"

- name: Unarchive (gunzip) the received tarball
  unarchive:
    src: "{{ sapp.edit.path }}/{{ sapp.name }}.bz2"
    dest: "{{ sapp.edit.path }}/"