- name: Reload deployer if push mode is full
  command: "{{ splunk.exec }} reload deploy-server -auth {{ splunk.admin_user }}:{{ splunk.password }} -timeout {{ retry_delay * retry_num }}"
  become: yes
  become_user: "{{ splunk.user }}"
  register: reload_depserver
  until: reload_depserver.rc == 0
  changed_when: reload_depserver.rc == 0
  retries: "{{ retry_num }}"
  delay: "{{ retry_delay }}"
  ignore_errors: yes
  no_log: "{{ hide_password }}"
  when: 