- name: Create archive on local server of app tree
  hosts: localhost
  become: no
  #See "archive-doc archive" for src & dest. e.g's.
  archive:
    path: "{{ sapp.location }}/{{ sapp.name }}"
    dest: "{{ sapp.tempfile.archname }}"
    format: bz2
    
- name: Copy archived file to deployment server
  include_tasks: tasks/put_app_op_deployer.yml    

- name: Reload deployment server
  include_tasks: tasks/initate_deployment.yml
