---

- name: PutApp - Push back to deployer
  unarchive:
    src: "{{ splunk_app.edit_path }}/{{ splunk_app.name }}.bz2"
    dest: "{{ splunk_app.source_path }}"
    owner: "{{ splunk.admin.user }}"
    group: "{{ splunk.admin.user }}"
    mode: '0700'