- name: PutApp - Copy archived file to deployment server
  include_tasks: tasks/put_app_onto_deployer.yml    

- name: PutApp - Unarchive the pushed {{ sapp.tempfile.arch_name }}
  vars_files:
  - splunk_vault.yml
  - vars/single_app_vars.yml
  
  tasks:
  - name: PutApp - Create {{ sapp.edit.path }} directory on localhost
    unarchive:
      src: "{{ sapp.tempfile.arch_name }}"
      dest: "{{ sapp.edit.path }}/"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'