- name: Copy archived file to deployment server
  include_tasks: tasks/put_app_onto_deployer.yml    

- name: Unarchive the pushed {{ sapp.tempfile.arch_name }}
  vars_files:
  - vars/single_app_vars.yml
  tasks:
  - name: Create {{ sapp.edit.path }} directory on localhost
    unarchive:
      src: "{{ sapp.tempfile.arch_name }}"
      dest: "{{ sapp.edit.path }}/"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: '0700'